In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
pd.pandas.set_option('display.max_columns',None)
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder,PowerTransformer,StandardScaler,MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import pickle
import warnings
warnings.filterwarnings(action="ignore")
from sklearn.model_selection import train_test_split

In [17]:
df=pd.read_csv("forest_outliers_removed1")

In [8]:
df.head()

Unnamed: 0  day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  \
0           0    1      6  2012           29  57  18   0.0  65.7  3.4   7.6   
1           1    2      6  2012           29  61  13   1.3  64.4  4.1   7.6   
2           2    3      6  2012           26  82  22  13.1  47.1  2.5   7.1   
3           3    4      6  2012           25  89  13   2.5  28.6  1.3   6.9   
4           4    5      6  2012           27  77  16   0.0  64.8  3.0  14.2   

   ISI  BUI  FWI   Classes  
0  1.3  3.4  0.5  not fire  
1  1.0  3.9  0.4  not fire  
2  0.3  2.7  0.1  not fire  
3  0.0  1.7  0.0  not fire  
4  1.2  3.9  0.5  not fire

In [9]:
df.drop(columns=['Unnamed: 0'],axis=1,inplace=True)

In [10]:
df['Classes']=df['Classes'].apply(lambda x:1 if x=='fire' else 0)

In [11]:
df.head()

day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  \
0    1      6  2012           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4   
1    2      6  2012           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9   
2    3      6  2012           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7   
3    4      6  2012           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7   
4    5      6  2012           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9   

   FWI  Classes  
0  0.5        0  
1  0.4        0  
2  0.1        0  
3  0.0        0  
4  0.5        0

In [12]:
X=df.drop(columns=['year','Classes'],axis=1)

In [13]:
y=df['Classes']

In [14]:
X

day  month  Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI
0      1      6           29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5
1      2      6           29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4
2      3      6           26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1
3      4      6           25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0
4      5      6           27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5
..   ...    ...          ...  ..  ..   ...   ...   ...   ...  ...   ...  ...
239   26      9           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5
240   27      9           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0
241   28      9           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2
242   29      9           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7
243   30      9           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5

[244 rows x 12 columns]

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [19]:
X_train.shape,X_test.shape

((183, 12), (61, 12))

In [21]:
lr=LogisticRegression()
pipe=Pipeline([
    ('lr',lr)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)

In [22]:
accuracy

0.9836065573770492

In [25]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[27  0]
 [ 1 33]]
classification report: 
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.97      0.99        34

    accuracy                           0.98        61
   macro avg       0.98      0.99      0.98        61
weighted avg       0.98      0.98      0.98        61



In [26]:
svc=SVC()
pipe=Pipeline([
    ('svc',svc)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)

In [27]:
accuracy

0.8688524590163934

In [28]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[25  2]
 [ 6 28]]
classification report: 
               precision    recall  f1-score   support

           0       0.81      0.93      0.86        27
           1       0.93      0.82      0.87        34

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.88      0.87      0.87        61



In [29]:
gaussian=GaussianNB()
pipe=Pipeline(
[
    ('gaussian',gaussian)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)

In [30]:
accuracy

0.9344262295081968

In [31]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[27  0]
 [ 4 30]]
classification report: 
               precision    recall  f1-score   support

           0       0.87      1.00      0.93        27
           1       1.00      0.88      0.94        34

    accuracy                           0.93        61
   macro avg       0.94      0.94      0.93        61
weighted avg       0.94      0.93      0.93        61



In [33]:
knn=KNeighborsClassifier()
pipe=Pipeline([
    ('knn',knn)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)



In [34]:
accuracy

0.9180327868852459

In [35]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[25  2]
 [ 3 31]]
classification report: 
               precision    recall  f1-score   support

           0       0.89      0.93      0.91        27
           1       0.94      0.91      0.93        34

    accuracy                           0.92        61
   macro avg       0.92      0.92      0.92        61
weighted avg       0.92      0.92      0.92        61



In [36]:
tree=DecisionTreeClassifier()
pipe=Pipeline([
    ('tree',tree)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)


In [37]:
accuracy

0.9672131147540983

In [38]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[26  1]
 [ 1 33]]
classification report: 
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        27
           1       0.97      0.97      0.97        34

    accuracy                           0.97        61
   macro avg       0.97      0.97      0.97        61
weighted avg       0.97      0.97      0.97        61



In [39]:
rf=RandomForestClassifier()
pipe=Pipeline([
    ('rf',rf)
])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)

In [40]:
accuracy

0.9836065573770492

In [41]:
print("confusion matrix: \n",confusion_matrix(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))

confusion matrix: 
 [[27  0]
 [ 1 33]]
classification report: 
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       1.00      0.97      0.99        34

    accuracy                           0.98        61
   macro avg       0.98      0.99      0.98        61
weighted avg       0.98      0.98      0.98        61



In [42]:
import json
result = X_test.to_json(orient="records")
parsed = json.loads(result)

In [43]:
parsed

[{'day': 16,
  'month': 8,
  'Temperature': 36,
  'RH': 61,
  'Ws': 18,
  'Rain': 0.3,
  'FFMC': 80.2,
  'DMC': 11.7,
  'DC': 90.4,
  'ISI': 2.8,
  'BUI': 17.6,
  'FWI': 4.2},
 {'day': 24,
  'month': 7,
  'Temperature': 33,
  'RH': 63,
  'Ws': 17,
  'Rain': 1.1,
  'FFMC': 72.8,
  'DMC': 20.9,
  'DC': 56.6,
  'ISI': 1.6,
  'BUI': 21.7,
  'FWI': 2.5},
 {'day': 6,
  'month': 8,
  'Temperature': 30,
  'RH': 54,
  'Ws': 14,
  'Rain': 3.1,
  'FFMC': 70.5,
  'DMC': 11.0,
  'DC': 9.1,
  'ISI': 1.3,
  'BUI': 10.5,
  'FWI': 0.8},
 {'day': 10,
  'month': 7,
  'Temperature': 34,
  'RH': 51,
  'Ws': 16,
  'Rain': 3.8,
  'FFMC': 77.5,
  'DMC': 8.0,
  'DC': 9.5,
  'ISI': 2.0,
  'BUI': 7.7,
  'FWI': 1.3},
 {'day': 14,
  'month': 6,
  'Temperature': 27,
  'RH': 79,
  'Ws': 16,
  'Rain': 0.7,
  'FFMC': 53.4,
  'DMC': 6.4,
  'DC': 7.3,
  'ISI': 0.5,
  'BUI': 6.1,
  'FWI': 0.3},
 {'day': 1,
  'month': 7,
  'Temperature': 28,
  'RH': 58,
  'Ws': 18,
  'Rain': 2.2,
  'FFMC': 63.7,
  'DMC': 3.2,
  'DC': 8.5,

In [45]:
pickle.dump(pipe,open('pipe_class2.pkl','wb'))

In [47]:
!pip install pymongo

  Using cached pymongo-4.7.2-cp311-cp311-win_amd64.whl.metadata (22 kB)
  Using cached dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Using cached pymongo-4.7.2-cp311-cp311-win_amd64.whl (484 kB)
Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)


In [53]:
import certifi

In [54]:
import pymongo
client = pymongo.MongoClient("mongodb+srv://tallojiharshith:tallojiharshith@cluster0.pyu7rs3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",tlsCAFile=certifi.where())

In [59]:
db = client.forest_fires
print(db)

Database(MongoClient(host=['ac-pqgccm2-shard-00-01.pyu7rs3.mongodb.net:27017', 'ac-pqgccm2-shard-00-02.pyu7rs3.mongodb.net:27017', 'ac-pqgccm2-shard-00-00.pyu7rs3.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-x2ptah-shard-0', tls=True, tlscafile='C:\\Anaconda\\Lib\\site-packages\\certifi\\cacert.pem'), 'forest_fires')


In [60]:
coll = db['classification_batch']

In [61]:
dict_test = {'day': 24, 'month': 6, 'RH': 68, 'Ws': 16, 'Rain': 0, 'FFMC': 85, 'DMC': 10, 'DC': 17,
                 'ISI': 4, 'BUI': 9, 'FWI': 5.3, 'classes': 0}

In [62]:
db.list_collection_names()

[]

In [63]:
coll.insert_many(parsed)

InsertManyResult([ObjectId('664c90c33a203086c21f0b4f'), ObjectId('664c90c33a203086c21f0b50'), ObjectId('664c90c33a203086c21f0b51'), ObjectId('664c90c33a203086c21f0b52'), ObjectId('664c90c33a203086c21f0b53'), ObjectId('664c90c33a203086c21f0b54'), ObjectId('664c90c33a203086c21f0b55'), ObjectId('664c90c33a203086c21f0b56'), ObjectId('664c90c33a203086c21f0b57'), ObjectId('664c90c33a203086c21f0b58'), ObjectId('664c90c33a203086c21f0b59'), ObjectId('664c90c33a203086c21f0b5a'), ObjectId('664c90c33a203086c21f0b5b'), ObjectId('664c90c33a203086c21f0b5c'), ObjectId('664c90c33a203086c21f0b5d'), ObjectId('664c90c33a203086c21f0b5e'), ObjectId('664c90c33a203086c21f0b5f'), ObjectId('664c90c33a203086c21f0b60'), ObjectId('664c90c33a203086c21f0b61'), ObjectId('664c90c33a203086c21f0b62'), ObjectId('664c90c33a203086c21f0b63'), ObjectId('664c90c33a203086c21f0b64'), ObjectId('664c90c33a203086c21f0b65'), ObjectId('664c90c33a203086c21f0b66'), ObjectId('664c90c33a203086c21f0b67'), ObjectId('664c90c33a203086c21f0b

In [64]:
pickle_model = pickle.load(open('pipe_class2.pkl','rb'))

In [65]:
dict_test ={'day':1, 'month':6, 'Temperature':26,'RH':57, 'Ws':18.0, 'Rain':0.00, 'FFMC':65.7000,
       'DMC':3.4, 'DC':7.6, 'ISI':1.3, 'BUI':3.4, 'FWI':0.5}

In [66]:
list(dict_test.values())

[1, 6, 26, 57, 18.0, 0.0, 65.7, 3.4, 7.6, 1.3, 3.4, 0.5]

In [67]:
input = np.array(list(dict_test.values())).reshape(1,12)

In [68]:
pipe.predict(input)[0]

0